### ISSUE TITLE
enumerating all paths that less than certain length

### ISSUE THREAD

**Issue by veriatl** [classicwuhao/Cyclone#9]
Hi, if I want to enumerate paths that are less than a certain length `n`, I currently write the following conditions manually:
```
enumerate for n-1 via ... reach ...
enumerate for n-2 via ... reach ...
...
enumerate for 2 via ... reach ...
``` 

is Cyclone provides a syntax to support this automatically?

**Comment by classicwuhao** [comment]
An enumerate statement will put Cyclone an very **expensive** mode. Depends on the size of a graph and its connected nodes, we may have a significant large number of possible paths just for a single n. This typically will consume a large amount of memory and CPU time. So it is probably not the best way to provide this functionality. 

However, APIs are designed and will be made available so users can use them to implement their algorithms based on their own purposes at their own cost.

**Comment by veriatl** [comment]
yeah, it makes sense. The user could do a linear search from `2` **up to** `n` to ensure termination.
